### ISSUE TITLE
Store DocRef as values.Ref

### ISSUE THREAD

**Issue by ptpaterson** [typescript-fun/typed-functional-fauna#5]
This is really more of a question to explore io-ts and your perspective of how to use it, rather than a strong opinion that it should change.

What benefit do you see to encoding a `DocRef` as something other than `values.Ref`?  While the graphQL API uses ID strings in results, just using FQL I think it makes more sense to handle the values.Ref directly.

In the example page, you `console.log(productDoc.data.owner.id)`, but it's not clear why id and collection name should be more accessible than the ref itself.

If we wanted to build a new query from this, for example, we would need to decode the product owner, then unwrap it from Either to use it, right?  Or rebuild a ref from `query` or `values`.

My thoughts are that it would be more practical to just use the prop already available from decoding the entire product.

I would rather, elsewhere in the application, do `q.Get(productDoc.data.owner)`, rather than `q.Get(q.Ref(q.Collection(productDoc.data.owner.collection), productDoc.data.owner.id))`

FaunaDocRef could be defined more concisely like:

```js
export const FaunaDocRef = new t.Type<values.Ref>(
  'FaunaDocRef',
  (u): u is values.Ref => u instanceof values.Ref
  (u, c) => (u instanceof values.Ref) 
      ? t.success(u)
      : t.failure(u, c),
  t.identity
)
```

**Comment by ptpaterson** [comment]
Okay, continuing to work, and I understand `t.Type` better now.  I see we can use the ref using `encode`.  I think like this:
```js
q.Get(FaunaDocRef.encode(productDoc.data.owner))
```

But that still feels unnecessary.

I do think that decoding and storing timestamp/date is very valuable, though!

**Comment by steida** [comment]
Sure, send PR.

**Comment by steida** [comment]
It's by design. It must be io-ts type/codec.

**Comment by steida** [comment]
@ptpaterson The problem is we have FaunaID branded type, to ensure someone will not pass an arbitrary string. And it's not compatible with string from values.Ref instance. 

Another problem is, there are really two representations of Fauna Ref. An instance and JSON. We would have to call Fauna driver not exported method parseJSON and then io-ts decode. 

That's what is really bad with the current Fauna driver implementation, it uses instances instead of JSONs. I hope Fauna will change it. Serialization and deserialization really suck with Class based approach.

**Comment by steida** [comment]
@ptpaterson Explained here https://forums.fauna.com/t/fauna-js-driver-should-use-jsons-instead-of-classes/172
